### ISSUE TITLE
Not working with Spatie HTML package

### ISSUE THREAD

**Issue by antick** [codestudiollc/laravel-totem#114]
This is what I get when I open the totem page-

Method Spatie\Html\Html::columnSort does not exist. (View: project\vendor\studio\laravel-totem\resources\views\tasks\index.blade.php)

I am using Spatie HTML package. Is there any way I can get a workaround for this?

**Comment by roshangautam** [comment]
I just tested this and installing Totem on a fresh copy of Laravel works fine.

What version of Laravel and Totem are you using? Also it would be really helpful if you can mention the steps to reproduce your issue.

**Comment by antick** [comment]
Thank you for the reply, Roshan.

I am using the latest version of Laravel and totem.

As I mentioned, I am using Spatie's HTML package, maybe that is what conflicts with Laravel collectives that Totem usage.

**Comment by roshangautam** [comment]
Thats very much possible. I have plans to convert Totem into a SPA using vue driven tables etc. which will eliminate the use of any html package (laravel collective/spatie) in the near future. For now, I am afraid, there's nothing much I can do to help you. You can use Laravel collective atm if it meets your requirements instead of Spaties HTML package.

Again, sorry for any inconvenience caused.
