### ISSUE TITLE
[REQUEST] compileParameters() do not works with multiple input options

### ISSUE THREAD

**Issue by benjamiis** [codestudiollc/laravel-totem#191]
When defining an option that expects an array input, each option value passed to the command should be prefixed with the option name:
email:send {--id=*}

We can call it like this :
php artisan email:send --id=1 --id=2

but after a call to Task->compileParameters() only the last options value is used.
Resulting in this example to get a call like this one :
php artisan email:send --id=2

**Comment by qschmick** [comment]
@benjamiis We currently don't support that command signature. Since we iterate over the passed in string we are current just setting the arrays keys with the value. In the example case we create a parameter array and set the key of `id` to a value of `1`. We then override that with a value of `2`.

Feel free to open a PR to handle this case, I can try and take a look but it will take me a while to have the free time to be honest.
