### ISSUE TITLE
Commands Not Running Even Though Listed

### ISSUE THREAD

**Issue by s1rc** [codestudiollc/laravel-totem#280]
Just switching from manually scheduling tasks into Totem. Everything is imported and `php artisan schedule:list` shows all commands correctly. However none of the commands run at their scheduled time, though manually executing through Totem does work.

Trying to debug locally if I create command to simply log an output, it shows up in list:

![image](https://user-images.githubusercontent.com/2073967/112900046-e8d74d00-90b0-11eb-805e-a2d62ef18a47.png)

* Enabling the command in Kernel.php logs to the log file correctly
* Enabling the command in Totem does not log anything from the command
* Enabling the command in both Kernel and Totem shows identical commands scheduled (see below)
* 
![image](https://user-images.githubusercontent.com/2073967/112901723-1c1adb80-90b3-11eb-9fbd-8b66712fb423.png)

Not sure if there is other configuration missing why this isn't working? 

Laravel Framework: `8.34.0`
Laravel Totem: `8.1.1`

**Comment by ikudosi** [comment]
I also noticed the commands were not running when upgrading to latest version. I downgrade to version 8.0.4 and tasks are now running however I don't see any execution results.

**Comment by s1rc** [comment]
@ikudosi thank you that did work, but no execution results as you mentioned.

**Comment by daniel-g-wood** [comment]
@ikudosi, @s1rc, Unfortunately, downgrading to 8.0.4 may not work because of the bug introduced in 8.0.3 (see #271). Can you try using version 8.0.2 and see if the issue persists? I've tried a few different things (including creating a new app with a task in Totem and running schedule:test) and I'm not able to reproduce the issue (the task still executes and adds to the results).

Are you getting any errors in your log files?

**Comment by s1rc** [comment]
@daniel-g-wood trying with 8.0.2, the tasks are running but no results. Now we are getting which wasn't in the logs with 8.0.4.

```
Undefined property: Illuminate\\Console\\Scheduling\\Event::$start at /var/www/vendor/studio/laravel-totem/src/Providers/ConsoleServiceProvider.php:44)
```

**Comment by daniel-g-wood** [comment]
@s1rc It doesn't look like going backwards is going to solve this. This might be the same issue as #278. Try using a standard Artisan command, and setting the queue driver to `sync`, and attempting to execute the command via the totem dashboard and also via `schedule:test` and see if you end up with any results in the database then.

**Comment by s1rc** [comment]
The default queue connection is already `sync` since we override already to different queues per job.

Manually triggering each job from Totem already worked ok, even on v8.1.1. The results display in Totem.

**Comment by ikudosi** [comment]
Updated to latest version (8.1.3) and still cannot get this to work. I see the test.txt being created but tasks are not firing on its scheduled time. Manually executing the task works by clicking on the checkmark.

When I run `php artisan schedule:list` this is the output:

![image](https://user-images.githubusercontent.com/5790073/119497475-9f168600-bd32-11eb-96c7-bd1bf587d430.png)

**Comment by kanhaiyam** [comment]
@s1rc @daniel-g-wood  Found the solution. 

There are a few Laravel protocols that you know and understand before I give you the solution to this,
When executing a task from totem dashboard, that task is being executed by PHP.
Similarly, when a job gets executed by the scheduler weather using **```schedule:test```** OR **```schedule:run```**, it gets executed by _**shell**_.  

Now, since the scheduler is overridden by Totem, totem create a temp log file at **storage path - storage/app/totem/** and deletes it after execution. And since it is getting executed by shell, the shell output and errors gets suppressed, hence we don't get to know about it.

So for your tasks to be executed by Totem Scheduler you should give proper permission to **storage path - storage/app/totem/** so that shell can create and delete file at the location.

**Comment by kanhaiyam** [comment]
@s1rc @daniel-g-wood Can you guys please verify if it solved your issue.

**Comment by shijie1991** [comment]
Laravel Framework 8.51.0
versions : * v8.1.4

无法自动运行

**Comment by s1rc** [comment]
@kanhaiyam I'd love to try but I can't even install totem anymore on a local env.  https://github.com/codestudiohq/laravel-totem/issues/290

**Comment by qschmick** [comment]
@kanhaiyam Please see #295 as there is a proposed solution to remove the local storage usage. Additionally, I had a similar issue of some commands running and others not when I used the do not overlap functionality. One of the jobs errors but the mutex entries were created by Laravel already but not cleaned up and they persisted. I could manually run but when running the commands via `schedule:run` they would be skipped. Not sure if the same issue or just related to the local storage. Hopefully after #295 is reviewed and released the issue will be resolved.

**Comment by kanhaiyam** [comment]
@qschmick This seems promising.

**Comment by qschmick** [comment]
New version released (https://github.com/codestudiohq/laravel-totem/releases/tag/v8.2.0). Let us know if it fixes the issue.

**Comment by kanhaiyam** [comment]
Thanks for the notification. Will check the results and get back to you soon.
