### ISSUE TITLE
Pusher error: The data content of this event exceeds the allowed maximum (10240 bytes)

### ISSUE THREAD

**Issue by oliworx** [codestudiollc/laravel-totem#303]
**Illuminate\Broadcasting\BroadcastException**
Pusher error: The data content of this event exceeds the allowed maximum (10240 bytes). See https://pusher.com/docs/channels/server_api/http-api#publishing-events for more info

One of the artisan commands is pruducing more than 300 lines of output.

Totem Version: 6.0.3

My workaround was to set `TOTEM_BROADCASTING_ENABLED` to `false` in the .env file

**Comment by qschmick** [comment]
@oliworx Apologies for the late response. Totem is broadcasting the entire output from your command. It would appear your command is just outputting a large payload which exceeds pushers limits.

Open to suggestions on expected behavior in a situations like this. My thoughts would be to add a config option to exclude command output in broadcast payloads.
