### ISSUE TITLE
Try to implement for multiple laravel instance but same database

### ISSUE THREAD

**Issue by mgip** [codestudiollc/laravel-totem#341]
Hello

I Try to implement for multiple laravel instance but same database, but when i disable in Intance #1 and tun artisan schedule:list has diferent result with the other laravel instance.

Is anyway to adapt to multiple instance

Other thing, i am looking the task_result on database, but show all task result is_active=0 include.. ¿why?

Thanks

**Comment by qschmick** [comment]
@mgip As the current implementation of Totem leverages a single database table it will not support this type of functionality. Each "instance" of your application is seen as the same because they are all pointing at the same DB.

Not sure how you are differentiating your instances for things like users and such.

If you want to put together a proposal for implementing this we'd be happy to review but it isn't currently something I'm working on implementing. Not sure about @roshangautam

**Comment by mgip** [comment]
> @mgip As the current implementation of Totem leverages a single database table it will not support this type of functionality. Each "instance" of your application is seen as the same because they are all pointing at the same DB.
> 
> Not sure how you are differentiating your instances for things like users and such.
> 
> If you want to put together a proposal for implementing this we'd be happy to review but it isn't currently something I'm working on implementing. Not sure about @roshangautam

Helloo

In fact i did, i just add a field on all tables "id_app", and in all insert and select routines the where sentence like

    ->where(['id_app'] => env('ID_APP'))

it's work, and add on AppServiceProvider some update of scheduler... like

    $task = (new EloquentTaskRepository())->check();

And on EloquentTaskRepository.php

    public function check()
    {
        $task = Task::query()->with('frequencies')->first();
        Updated::dispatch($task);
        return $task;
    }

That makes sure it's in sync the app instace.
I don't know if it can be made more elegant, but at least it works.

Now My Problem:

When i do "artisan schedule:list", show me all task, the "is_active=0" and is not filter by id_app....


I hope you have understood well.
Thx a lot.
